### ISSUE TITLE
Looking to deploy and do development on new plugins

### ISSUE THREAD

**Issue by ghost** [CalthorpeAnalytics/UrbanFootprint#2]
I am looking to deploy Urban Footprint and develop new plugins for it. I am a contractor working on a project for the EPA to integrate the SWMM tool into Urban Footprint but the readthedocs and readme here leave a lot of gaps on getting started. I see that it is a django based application. But also that there are lots of requirements including Hadoop.

Basically I am looking for an installation/getting started guide.

**Comment by shkfnly** [comment]
There aren't even installation instructions for programmers
