### ISSUE TITLE
Username and password to access the VM

### ISSUE THREAD

**Issue by firmanhadi** [CalthorpeAnalytics/urbanfootprint#7]
Hello all,

Thank you for providing easy installation to localhost using prebuilt-VM.

I would like to ask the username and password to access the VM.
Thank you.

Regards,

Firman Hadi.

<img width="832" alt="screen shot 2017-05-04 at 12 25 43" src="https://cloud.githubusercontent.com/assets/7415563/25691436/118874fe-30c5-11e7-9d07-e4286a95aef1.png">

**Comment by jalessio** [comment]
@firmanhadi The default credentials for ssh'ing to this VM are:
```
username: vagrant
password: vagrant
```
This follows the Vagrant  standards, which are detailed here:
https://www.vagrantup.com/docs/boxes/base.html#default-user-settings

**Comment by firmanhadi** [comment]
@jalessio Thank you very much 👍
