### ISSUE TITLE
Unsuccessful install on windows machine

### ISSUE THREAD

**Issue by ghost** [CalthorpeAnalytics/urbanfootprint#8]
Hi, 

I tried an install on my windows 7 laptop but failed. I used this option:

Download and install Git-bash (Windows only) -- A quick way to get a bash prompt on Windows

I executed "Git Bash" from start menu and it opened a command window. I typed the command in the command window:

curl https://raw.githubusercontent.com/CalthorpeAnalytics/urbanfootprint/master/get-uf.sh | bash

I used the "|" symbol that is the shift of the backslash key.

It tried to start urban footprint but it returned message:

100.0% bash: line 21 : vagrant: Command not found. Urban Footprint quickstart is complete. Open your web browser to: 

http://localhost: 3333/footprint/

When I opened chrome, it failed to fiind this page.

**Comment by jalessio** [comment]
@GienVW Looks like you don't have "vagrant" installed. See the [_Quickstart Prerequisites for Mac OS X and MS Windows_](https://github.com/CalthorpeAnalytics/urbanfootprint#quickstart-prerequisites-for-mac-os-x-and-ms-windows) for installation instructions.

I created PR #9 which should make the error message a bit more obvious.

**Comment by ghost** [comment]
OK. Thanks. Just to confirm then, I have to actually execute all 3 instructions:

Download and install VirtualBox -- VirtualBox allows us to create a Linux Virtual Machine
Download and install Vagrant -- A command line tool for interacting with VirtualBox and building the UF virtual machine
Download and install Git-bash (Windows only) -- A quick way to get a bash prompt on Windows

Sorry. Newbie. If all 3 have to be done, maybe would be clearer for newbies to explcitly state that all 3 of these steps have to be done in sequence. When I looked at these points, I interpreted that I should pick one of these.

**Comment by ghost** [comment]
I installed and ran the other two programs, Virtualbox and Vagrant. When I executed curl instruction in Git Bash, it downloaded urban footprint and executed all instructions up to and including running "pre-boot" VM customizations.

When it tried to boot VM, it ran into an error. Error message was: 

There was an error while executing "VboxManage", a CLI used by Vagrant for controlling Virtualbox. The command and stderr is shown below,

Command: [startvm", "0a475273-767e-4765-8000-b033fa748342", "--type", "headless"]

Stderr: VboxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VVBoxManage.exe: error Details: code E-FAIL <0x80004005>, component ConsoleWrap, interface IConsole

**Comment by jalessio** [comment]
This means that your computer either does not support or is not configured to run "virtualization". This is, unfortunately, well beyond the level of support I can offer. You might start by just searching for that error message:

[Search for _"VT-x is disabled in the BIOS for all CPU modes"_](https://www.google.com/search?q=VT-x+is+disabled+in+the+BIOS+for+all+CPU+modes)

**Comment by ghost** [comment]
OK. Thanks I went to web and found how to do this. There's a ton of Youtube videos on how to do this:

https://www.youtube.com/results?search_query=virtual+box+bios+all+cpu+modes

As per instructions, like this one:

https://www.youtube.com/watch?v=ERnKeUMEFXU

 I just went into Virtualbox to check under "system" menu that the  "Enable PAE/NX is checked off"
then went to the system BIOS on my Win 7 machine via entering startup boot menu such as shown here:

https://www.youtube.com/watch?v=OA_58fFGp2k

and found the Intel Virtualization Technology (enable/disable) switch. It was disabled. I enabled it.

It was just the last part of Curl that failed. If I run curl again, will it try to download urbanfootprint again? If so, I don't want to wait another 4 hours to download. I tried just executing VboxManage in Git Bash but it couldn't find the command. Please advise.

**Comment by ghost** [comment]
I just ran Curl after installing Virtualbox and it works fine. Just going to go through the tutorials now. Thanks so much for the help.
